{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name}}
  annotations:
    kubernetes.io/ingress.allow-http: "true"
spec:
  {{- toYaml .Values.ingress.spec | nindent 12 }}
  {{- end }}